locals {
  domains_http = [
    "*.ves.volterra.io",
    "downloads.volterra.io",
    "*.blob.core.windows.net",
    "volterra.azurecr.io",
    "vesio.azureedge.net",
    "*.azure.com",
    "*.microsoftonline.com",
    "*.amazonaws.com",
    "docker.io",
    "docker.com",
    "*.gcr.io",
    "gcr.io",
    "storage.googleapis.com",
    "update.release.core-os.net",
    "quay.io",
    "api.bcti.brightcloud.com",
  ]

  domains_dns = [
    "traffic-router-0.cdn-gc.ves.volterr",
    "traffic-router-1.cdn-gc.ves.volterr",
    "cdn.ves.volterra.io",
  ]

  domains_bd = [
    "ibd-webus.fastcache.net",
    "ibd-webemea.fastcache.net",
    "ibd-webapac.fastcache.net",
    "ibd-webemea2.fastcache.net",
  ]

  domains_smsv2 = [
    "tr2-tor-nodes.re.ves.volterra.io",
    "ty8-tky-nodes.re.ves.volterra.io",
    "dc12-ash-nodes.re.ves.volterra.io",
    "sy5-syd-nodes.re.ves.volterra.io",
    "sg3-sin-nodes.re.ves.volterra.io",
    "os1-osa-nodes.re.ves.volterra.io",
    "sif-che-nodes.re.ves.volterra.io",
    "sds3-tel-nodes.re.ves.volterra.io",
    "ams9-ams-nodes.re.ves.volterra.io",
    "mb2-mum-nodes.re.ves.volterra.io",
    "pa4-par-nodes.re.ves.volterra.io",
    "dx1-dxb-nodes.re.ves.volterra.io",
    "mtl7-mon-nodes.re.ves.volterra.io",
    "ls1-lis-nodes.re.ves.volterra.io",
    "me1-mel-nodes.re.ves.volterra.io",
    "sto6-sto-nodes.re.ves.volterra.io",
    "fr4-fra-nodes.re.ves.volterra.io",
    "dal3-dal-nodes.re.ves.volterra.io",
    "tn2-lon-nodes.re.ves.volterra.io",
    "pa2-par-nodes.re.ves.volterra.io",
    "sp4-sao-nodes.re.ves.volterra.io",
    "ny8-nyc-nodes.re.ves.volterra.io",
    "md2-mad-nodes.re.ves.volterra.io",
    "hk2-hkg-nodes.re.ves.volterra.io",
    "jk1-jkt-nodes.re.ves.volterra.io",
    "sv10-sjc-nodes.re.ves.volterra.io",
    "wes-sea-nodes.re.ves.volterra.io",
    "register.ves.volterra.io",
    "register-tls.ves.volterra.io",
    "myip.volterra.io",
    "downloads.volterra.io",
    "gcr.download.volterra.io",
    "blindfold.ves.volterra.io",
    "identityauthority.ves.volterra.io",
    "waferdatasetsprod.download.volterra.io",
    "cc-whitelist.download.volterra.io",
    "api.bcti.download.volterra.io",
    "api.bcss.download.volterra.io",
    "api-dualstack.download.volterra.io",
    "localdb-url-daily.brightcloud.com",
    "localdb-url-rtu.brightcloud.com",
    "localdb-ip-daily.brightcloud.com",
    "localdb-ipv6-daily.brightcloud.com",
    "localdb-ip-rtu.brightcloud.com",
  ]

}
